name: Android Release

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12.x'
          cache: 'gradle'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.1'
          cache: true

      - name: Get Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --split-per-abi

      - name: Push to release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/app-arm64-v8a-release.apk"
          token: ${{ secrets.TOKEN }}
          release_name: "Release v1.0.0"
          release_body: "Release"
          tag: "v1.0.0"
          draft: false